#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : weakrefmethod
Version  : 1.0.3
Release  : 2
URL      : https://files.pythonhosted.org/packages/99/82/73a21e3eab9a1ff76d12375f7301fba5c6325b9598eed0ae5b0cf5243656/weakrefmethod-1.0.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/99/82/73a21e3eab9a1ff76d12375f7301fba5c6325b9598eed0ae5b0cf5243656/weakrefmethod-1.0.3.tar.gz
Summary  : A WeakMethod class for storing bound methods using weak references.
Group    : Development/Tools
License  : Python-2.0
Requires: weakrefmethod-python3
Requires: weakrefmethod-python
BuildRequires : buildreq-distutils3
BuildRequires : unittest2

%description
weakrefmethod
=============
Backport of WeakMethod from Python 3.4 to Python 2.6+

%package python
Summary: python components for the weakrefmethod package.
Group: Default
Requires: weakrefmethod-python3

%description python
python components for the weakrefmethod package.


%package python3
Summary: python3 components for the weakrefmethod package.
Group: Default
Requires: python3-core

%description python3
python3 components for the weakrefmethod package.


%prep
%setup -q -n weakrefmethod-1.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533874338
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
